version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    ports:
      - 5001:5001
    volumes:
      - ./backend:/app
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 1234:1234
    volumes:
      - ./frontend:/app
      - /app/node_modules