version: "3.8"
services:
  starter-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    ports:
      - 5001:5001
    volumes:
      - ./backend:/app
    depends_on:
      - starter-db
    links:
      - starter-db
    restart: on-failure:5
    environment:
      - GO_ENV=development
  starter-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 1235:1234
    volumes:
      - ./frontend:/app/
      - /app/node_modules
  starter-db:
    image: cockroachdb/cockroach:latest-v22.1
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - "${PWD}/cockroach-data/db:/cockroach/cockroach-data"
